### ISSUE TITLE
Feature: User can post a todo list item

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/to-do-app#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 User can see an input field where they can type in a to-do item

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user goes to the main page they will see a field where they can type a todo-list item. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to add to-do-list inputs

### ☁️ Server Tasks

- [x] Update `server/index.js` to create a 'post' route that will create a user input
- [x] Set the parameters of the post route
- [x] Check that the post is being created and updated 
- [x] Test with HTTPie
- [x] Create a test using jest to see if it will post
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to handle the to-do application posts 
- [x] Create a text field component that will add the user's input
- [x] Update state when user types in the field -- Use React Redux for state management
- [x] Create a hook that will process and send the user data to the server
- [x] Handle errors 
- [x] Check that the user's data is being sent to the database

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
