### ISSUE TITLE
Feature: User can view a calendar 

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/to-do-app#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a calendar 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User will be able to view a calendar that will eventually allow them to keep track of their daily todos and what they've accomplished each day. They will also be able to set reminders for themselves or schedule recurring todos. 

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to contain a calendar for the user to view
- [x] Incorporate a calendar that can be clickable
- [x] Link the component to the homepage as a new view

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
