### ISSUE TITLE
Feature: User can view todos on calendar

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/to-do-app#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their todos on a calendar

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once a user is looking at the calendar, they will be able to see their list of todos for a particular day of the week. Unscheduled todos will appear each day. When a todo has been completed, it will be found underneath that particular day's todo. Any incomplete todo will carry over to the next day. 

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to include a `scheduled date` column
- [ ] Update `schema.sql` to include a `completed at` column
- [ ] Update `data.sql` to include default data for "todos" list 

### ☁️ Server Tasks

- [ ] Update `server/index.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Update `calendar` to get todos list 
- [ ] Render todos list on calendar
- [ ] Update `calendar` component to filter todos based on selected calendar date 
- [ ] Update `calendar` component to allow user to check off specific todos for each date 
- [ ] Allow user to view both completed and incomplete todos for a particular date (show both)

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
