### ISSUE TITLE
Feature: User can view todo list

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/to-do-app#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view todo list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user logs onto the page, they will be able to see a list of reviews. They will also see their new item added to the list after submission.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Practice retrieving lists

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a get route that will retrieve the todo items
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display the list of todo items
- [x] Fetch from server the list of items 
- [x] Update the state using redux to display the list
- [x] Update the list when a user submits a new item

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
