### ISSUE TITLE
Feature: User can update todolist 

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/to-do-app#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can update todolist 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to see their posted todoList item populate in the todoLists and be able to click on the checkbox to change the TodoList item to be 'completed'. Once marked complete, the item will have a strikethrough

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to change the 'isCompleted' attribute of a todoList Item

### ☁️ Server Tasks

- [x] Update `server/index.js` to create a put route that will edit the 'isCompleted' attribute
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update todoList form to update the todos state 
- [x] Check that DOM is updated when a new event is added to the todoList
- [x] Add event handler to todoItem to check for user clicking on checkbox
- [x] Create a function that will send request to server for updating the 'isCompleted'
- [x] Create a thunk component that will handle asynchronous request to server 
- [x] Update todos state
- [x] Check that dom is rendering successfully 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
